### ISSUE TITLE
Add physical tests for surface fluxes

### ISSUE THREAD

**Issue by szy21** [CliMA/SurfaceFluxes.jl#73]
## Purpose
Add physical tests for surface fluxes based on Monin-Obukhov similarity theory

## Cost/Benefits/Risks
cost: Time of a few (2) atmos team members
benefits: Surface fluxes needs some substantial refactoring, mostly for EDMF and also for the land. Having physical tests can ensure we don't break things (as we did a few times before!)
risks: We are designing our own tests as there are not many existing tests that we can follow

## People and Personnel
(@ the personnel required/requested to implement the software solution)
- Lead: @szy21 
- Collaborators: @akshaysridhar 
- Reviewers: @tapios ?

## Components
see task breakdown

## Inputs
N/A

## Results and deliverables
Tests that are run in ci

## Task Breakdown And Tentative Due Date
- [ ] Test `recover_profile` yields logarithmic velocity and thermodynamic profiles under neutral condition, or in the stable/unstable regime but close to the neutral condition
- [ ] Test the sign of surface fluxes
- - `obukhov_length` should be negative for unstable regime and positive for stable regime
- - `compute_buoyanc_flux` should be positive for unstable regime and negative for stable regime
- - Momentum flux should be negative
- - For dry case, sensible heat flux should be positive for unstable regime and negative for stable regime
- - For moist case, evaporation should be positive if q_sfc > q_int and negative if q_sfc < q_int (Any other signs that we can check for moist case?)
- [ ] Compare the magnitude of surface fluxes with Figures 5 and 7 in [Nashizawa and Kitamura 2018](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2018MS001534). The results won't be exactly the same as we don't have the input values, but the magnitude should be comparable.

## Proposed Delivery Date
Nov 18, 2022 (We can prioritize it if needed by EDMF)

**Comment by tapios** [comment]
LGTM. However, please note that the momentum flux can have either sign (depending on sign of velocity);

**Comment by LenkaNovak** [comment]
Akshay already has a qualitative comparison with ERA-5, but we're currently exploring whether we can easily extend this to use surface data instead of data on a pressure level, for an even better agreement. I'll defer to @akshaysridhar for the timelines, since he's leading the effort.
