### ISSUE TITLE
Roughness Sublayer Models

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/SurfaceFluxes.jl#84]
## Purpose
Technical Notes on the implementation of Roughness Sublayer Models (RSLs) within the SurfaceFluxes.jl package. The goal is to design RSL model components and interfaces such that they may be used as an optional extension to the existing equations for the Monin-Obukhov Similarity Theory (MOST). 

## Cost/Benefits/Risks
Cost: Time for equation / documentation verification. No new research required for current scope of project - models for RSLs of varying complexity exist. The first step of this broader task is to incorporate those models into the SurfaceFluxes package, following which we can investigate their behaviour in the ClimaESM, and suggest improvements.  
Benefits: Extended MOST for RSLs (useful for simulations where canopy interactions play an important role). 
Risks: This is a necessary component of a complete package concerning surface fluxes so an implementation is required in any case. Few direct risks. Schedule risks with additional projects that contributors are involved in. 

## People and Personnel
(@ the personnel required/requested to implement the software solution)
- Lead: @akshaysridhar 
- Collaborators: @LenkaNovak @szy21 @kmdeck (For content review, interface suggestions and general advice on test cases)
- Reviewers: TBD. 

## Results and deliverables
- Tested RSL models for use in simulations of canopy induced turbulence. 

## Task Breakdown And Tentative Due Date (TODO: Granular task descriptions) 
- [ ] Documentation for RSL models (specifically w.r.t current choice of interfaces in this package). This exists in part in our Overleaf design-docs but needs to be included in the software documentation. 
- [ ] Prototype RSL model (Physick and Garratt (1995)) https://link.springer.com/article/10.1007/BF00715710
- [ ] Extension: Wang and Cionco (2007) https://apps.dtic.mil>sti>pdfs>ADA470616
- [ ] Extension: Bonan et al. (2018) https://doi.org/10.5194/gmd-11-1467-2018
- [ ] Tests for each of the above submodels. 
TODO: Track through Github issues. 

## Proposed Delivery Date
(TBD) General target is for PG95 RSL to be in by Feb Sprint. Stretch to include the more complex versions by then.

***

## CC
@cmbengue @tapios @simonbyrne

**Comment by tapios** [comment]
Looks good.

**Comment by akshaysridhar** [comment]
Closed by https://github.com/CliMA/SurfaceFluxes.jl/pull/258
